### ISSUE TITLE
needs support to have option to add background image for input slider

### ISSUE THREAD

**Issue by Tarun-555** [n3r4zzurr0/react-range-slider-input#6]
can we have properties where user can add customizable background images for slider instead of only having colors

**Comment by n3r4zzurr0** [comment]
You can already do that with some custom CSS. I have created a quick [demo on CodeSandbox](https://codesandbox.io/s/adoring-cache-cyq7vt?file=/src/styles.css).

```css
.range-slider .range-slider__range {
    background-image: url("...");
}
```
